### ISSUE TITLE
Revamp lock.

### ISSUE THREAD

**Issue by C7alt** [01000011-00110111/School-Chat#100]
- [x] Make a lock that locks all users besides the chat room owner, mods, or  devs or admins.
- [x] Make a lock that locks all users in the chat room for everyone but for devs or admins.
- [x] Make locks done by devs and admins lock everyone but devs/admins
- [x] make norm lock just like the norm lock currently working
- [x] allow devs and admins to use both a admin lock and a norm lock
##
I will reword it later

**Comment by 01000011-00110111** [comment]
Just make a extra check to see what type of lock to use for devs/admins

**Comment by 01000011-00110111** [comment]
Done
