### ISSUE TITLE
Separate customize_accounts into separate functions

### ISSUE THREAD

**Issue by cserver45** [01000011-00110111/School-Chat#105]
Maybe its own file?

This will reduce the line count in main.py significantly

**Comment by cserver45** [comment]
I'm going to put the functions in accounting.py

**Comment by 01000011-00110111** [comment]
That's why I made the file for account related code.

**Comment by cserver45** [comment]
I may tackle this tomorrow, so I don't get completely burnt out from the game code

**Comment by cserver45** [comment]
we will probably have to merge database-rework into main again, just to keep all db changes in the PR
