### ISSUE TITLE
Rework moderation

### ISSUE THREAD

**Issue by 01000011-00110111** [01000011-00110111/School-Chat#120]
This will make moderating the chat a lot more easier and get the very old/bad system updated to run a lot better.

**Comment by cserver45** [comment]
I can see us doing something like this to remove redundant code with `$sudo ban` and such, but what else?

**Comment by cserver45** [comment]
Changed the PR for this issue to the `commands-rework` branch, as it will be done there now I would assume

**Comment by cserver45** [comment]
is the moderation stuff working? (I would assume so, you had said all cmds were working)

**Comment by 01000011-00110111** [comment]
That was just a fix we need to add back all the moderation commands

**Comment by 01000011-00110111** [comment]
When we get a better idea of the system Ill make a new issue with the idea.
