### ISSUE TITLE
Chat Mobile Development

### ISSUE THREAD

**Issue by CastyiGlitchxz** [01000011-00110111/School-Chat#129]
- [ ] Main Chat Revamp
- [x] Fix Sidenav
- [ ] Fit to screen
- [ ] #131
- [ ] Fix Login screen

**Comment by cserver45** [comment]
are we not doing notifications on mobile then? (if so, cross out the checklist item with `~~message to be crossed out~~`

**Comment by cserver45** [comment]
understood
