### ISSUE TITLE
Add scripts/add-ons

### ISSUE THREAD

**Issue by 01000011-00110111** [01000011-00110111/School-Chat#133]
The basic idea is we make it so the user can add there own functionality and features to the chat

**Comment by cserver45** [comment]
I was thinking of doing something like this for games (so it actually becomes newgrounds lol), where all you need to do is dump the folder for the game, and it would add it to the selection menu (or the randomizer for the game of the day)

**Comment by 01000011-00110111** [comment]
Its done
