### ISSUE TITLE
theme issues

### ISSUE THREAD

**Issue by HackerHarper2026** [01000011-00110111/School-Chat#139]
As "the theme maker", I need to be able to change the Online List Text, "Message:", and Online List separation line colors to maximize theme capabilities.

**Comment by 01000011-00110111** [comment]
We have it set to white as a color that no one will use

**Comment by CastyiGlitchxz** [comment]
Don't worry @HackerHarper2026 I plan on doing that when I start to fully revamp the Theme Maker.

**Comment by cserver45** [comment]
We really should put the theme maker in its own repo, instead of just being on replit

**Comment by CastyiGlitchxz** [comment]
@cserver45 you really think so?

**Comment by cserver45** [comment]
if you do said revamp, I say it deserves a repo
