### ISSUE TITLE
Rework the database code

### ISSUE THREAD

**Issue by 01000011-00110111** [01000011-00110111/School-Chat#141]
The current way we use the database is slow and inefficient. The plan is to improve the efficiency and speed of the code wile making it easier to add new features to the existing code.
## List to do:

- [x] build database.py
- [x] move login to new db system
- [x] move account signup to new db system
- [x] move user data retrieval to new db system
- [x] move chat rooms to new db system
- [x] move sending to new db system
~~move commands to new db system~~ #77 
- [x] move chat.py to new db system
- [x] move online list to new db system
- [x] bug fix for hours
- [x] optimize and organize
- [x] reduce amount of funcs
## extra to do:

~~improve old commands with new system~~
- [x] change the key file to a config file

**Comment by 01000011-00110111** [comment]
Started the work on it main is mostly done and on to the room. I still need to rework the dev db to run with the new system

**Comment by 01000011-00110111** [comment]
its off main now and main now is protected so a PR is a requirement to add it there

**Comment by 01000011-00110111** [comment]
Getting some good progress on the rework got signup and login working

**Comment by 01000011-00110111** [comment]
I'm thinking to rework commands entirely and have a folder hold the commands files (making a separate files for what the commands effects. example online commands go to online.py).

**Comment by 01000011-00110111** [comment]
#### here is my idea:

have cmds.py have checks and other stuff before running commands then go to the commands folder and into the file that has the command

**Comment by cserver45** [comment]
This could go 2 ways:
- Make the command system very modular, and make it be the plug-in system (so abolishing the Addons.py file you had before)
**OR**
- Become receptive for similar commands, this could be solved by adding support for aliases 

I say do it just for future sanity

**Comment by 01000011-00110111** [comment]
Id say we are done with the main task in the to do list

**Comment by 01000011-00110111** [comment]
ok
