### ISSUE TITLE
Add real private messaging 

### ISSUE THREAD

**Issue by 01000011-00110111** [01000011-00110111/School-Chat#142]
Yes, you could add a private chat room with a certain user and chat like that but It takes up space in the list and we could add it and make it fit in a separate area.

**Comment by 01000011-00110111** [comment]
This wouldn't take as long as someone would expect I could build it for 1.2 or do throw it in a patch fix.

**Comment by 01000011-00110111** [comment]
1.2 will be the chat page revamp and DB rework. And this will be ether a in a patch fix update for 1.2 or put it in 1.3.

**Comment by cserver45** [comment]
I say we push this back to v1.4, so we can get v1.3 out soon, as all other things that are need to be done are small ones we probably could knock out in a day or two

**Comment by 01000011-00110111** [comment]
This is basically done just getting some sending aspects and filtering done

**Comment by cserver45** [comment]
well then I'll readd it to v1.3 then

**Comment by cserver45** [comment]
notes: will combine on_message to check the length of id, if its 12 chars, do private message pipeline, otherwise do normal pipeline

**Comment by 01000011-00110111** [comment]
That's a lot better then what I did
