### ISSUE TITLE
fix room commands

### ISSUE THREAD

**Issue by cserver45** [01000011-00110111/School-Chat#149]
Blacklist and Whitelist are currently broken

**Comment by cserver45** [comment]
should we link this to the `commands-rework` branch? (the command will be revamped anyway iirc)

**Comment by cserver45** [comment]
are these fixed? (as in, they work)

**Comment by 01000011-00110111** [comment]
Only reset chat is added so I guess you could call it fixed

**Comment by cserver45** [comment]
and I guess creation of rooms by users will be done in v1.4?

**Comment by 01000011-00110111** [comment]
I'm thinking about moving most room commands to buttons

**Comment by 01000011-00110111** [comment]
For now just creating rooms will be added and the rest will be in 1.4
