### ISSUE TITLE
Create a setup func

### ISSUE THREAD

**Issue by 01000011-00110111** [01000011-00110111/School-Chat#158]
This will make creating the chat server easier

**Comment by cserver45** [comment]
*how many times do I need to mention this* not a setup.py, a setup **function**

(I get what you mean, the name just annoys me is all)

**Comment by 01000011-00110111** [comment]
NO i forgot what you said

**Comment by 01000011-00110111** [comment]
fixed

**Comment by cserver45** [comment]
thank you

**Comment by 01000011-00110111** [comment]
started in the setup func in the image branch

**Comment by 01000011-00110111** [comment]
ill leave the rest of the func to you. there is not much left
