### ISSUE TITLE
Fix hyperlink

### ISSUE THREAD

**Issue by 01000011-00110111** [01000011-00110111/School-Chat#165]
I have no clue how so good luck @cserver45

**Comment by cserver45** [comment]
Wdym fix, it is fixed and working?

**Comment by cserver45** [comment]
:facepalm: my fault, patch PR is on the way, because I can't force-push to `v1.3`, which is annoying

**Comment by 01000011-00110111** [comment]
I'll try to give you perms to force commit to any branch (maybe not main I don't remember the perms I put in it)
