### ISSUE TITLE
Implementing more themes

### ISSUE THREAD

**Issue by cserver45** [01000011-00110111/School-Chat#3]
* [ ] school theme
* [ ] Christmas
* [ ] New years
* [ ] Thanksgivings
* [ ] Halloween
* [ ] 4th of July
* [ ] summer (cause why not)
* [ ] others

**Comment by 01000011-00110111** [comment]
One year old and still not done yet. It's very easy to get done so can someone please work on it.

**Comment by 01000011-00110111** [comment]
This issue is now 1 year old

**Comment by cserver45** [comment]
yep

**Comment by 01000011-00110111** [comment]
almost 2 now

**Comment by 01000011-00110111** [comment]
Well we added a theme maker, so now this issue is redundant enough to be closed.
