### ISSUE TITLE
add more checks to creating and editings accounts

### ISSUE THREAD

**Issue by 01000011-00110111** [01000011-00110111/School-Chat#88]
We are missing some checks in creating and editing accounts.
The following is missing:
- [x] Add a check on how long is a role
- [x] check if a username, display name, or role has a inappropriate language
- [x] a check to see if html is used in display name, role, or profile

I might be missing some so add some if found out

**Comment by C7alt** [comment]
isin't the last one part of #85 aswell?

**Comment by cserver45** [comment]
added html checks
