### ISSUE TITLE
Redesign messages 

### ISSUE THREAD

**Issue by 01000011-00110111** [01000011-00110111/School-Chat#93]
### Current:
[ Time ] (pfp) username (role) - message.

### Ideas:
- [ Time ] (pfp) username - message.
- (pfp) [ Time ] username - message

**Comment by 01000011-00110111** [comment]
MIght

**Comment by cserver45** [comment]
I say we leave it as [time] (pfp) because I would think (pfp) coming first would make the [time] look out of place

**Comment by 01000011-00110111** [comment]
I agree with that. I also think we should rework time it's ok but we can do a lot better.

**Comment by cserver45** [comment]
This seems like a simple issue to do, all we need to do is drop `role` from messages, which is just a db change, along with some lines of code removed

Now for revamping time, I say it's fine the way it is, but if you want it to be dynamically changing, like how discord does it, then go ahead and do that (make a new issue for it tho)

**Comment by 01000011-00110111** [comment]
Id say for now no need to rework it
