### ISSUE TITLE
Make a ban/mute appeal and request.

### ISSUE THREAD

**Issue by 01000011-00110111** [01000011-00110111/School-Chat#98]
This will allow you to appeal you mute (ban will most likely not happen) or request for a mute and for mods request bans.
##
### Features:
- [ ] Allow users to make a mute request or a appeal.
- [ ] Allow mods to make a ban request.
- [ ] Send the request or appeal to the mod chat if its from a user and send it to dev chat if its from a mod.
- [ ] make the request list show up every few hours in the chats unless its empty.
##
### Reason:
This is to improve moderation of the chat to make sure the chat stays a place that isn't chaos or disorder.

**Comment by cserver45** [comment]
something like `/requests`

**Comment by 01000011-00110111** [comment]
That is a good idea

**Comment by cserver45** [comment]
then that's how its gonna be then

**Comment by 01000011-00110111** [comment]
I'm kinda thinking of not adding this

**Comment by 01000011-00110111** [comment]
How about its just a report command. its way easier and makes more sense
